### ISSUE TITLE
Create a gh-pages site

### ISSUE THREAD

**Issue by Sparrow0hawk** [ARCTraining/swd5_sc_py#1]
To make it easier to share course details here it'd be good to migrate this to jupyter-books to quickly create a course page.

It won't fit within our existing formats but should work for what we want.

**Comment by patricia-ternes** [comment]
I came here to do the same.
Let me know if you want help.

**Comment by Sparrow0hawk** [comment]
Going to have a go once this training has wrapped but I created a [branch](https://github.com/ARCTraining/swd5_sc_py/tree/reformat-jbbook) you're welcome to check.

**Comment by patricia-ternes** [comment]
@Sparrow0hawk we forgot Github Action do deploy the book

<https://github.com/ARCTraining/template-jb-docs/blob/main/.github/workflows/deploy-book.yml>

**Comment by Sparrow0hawk** [comment]
We did! I just submitted a new PR with them #3

**Comment by Sparrow0hawk** [comment]
Resolved in #3
